from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
import os
from pathlib import Path
import subprocess
import sys
from typing import Any
from uuid import uuid4


@dataclass
class UATStep:
    name: str
    passed: bool
    details: str


def _set_uat_environment(db_path: Path) -> None:
    os.environ["DATABASE_URL"] = f"sqlite+aiosqlite:///{db_path.as_posix()}"
    os.environ["AUTH_SECRET_KEY"] = "uat-secret-key-with-more-than-thirty-two-characters"
    os.environ["AUTH_COOKIE_SECURE"] = "false"
    os.environ["QUEUE_DRIVER"] = "inline"
    os.environ["DEBUG"] = "false"


def _run_migrations(repo_backend: Path) -> None:
    subprocess.run(
        [sys.executable, "-m", "alembic", "upgrade", "head"],
        cwd=repo_backend,
        check=True,
        env=os.environ.copy(),
    )


def _create_report(*, repo_backend: Path, steps: list[UATStep], started_at: datetime, finished_at: datetime) -> Path:
    date_str = finished_at.date().isoformat()
    report_path = repo_backend / "docs" / f"UAT_SIGNOFF_{date_str}.md"
    all_passed = all(step.passed for step in steps)
    status = "PASS" if all_passed else "FAIL"

    lines = [
        "# UAT Sign-off",
        "",
        f"- Date: {finished_at.isoformat()}",
        f"- Duration Seconds: {(finished_at - started_at).total_seconds():.2f}",
        f"- Result: {status}",
        "",
        "## Step Results",
        "",
    ]
    for step in steps:
        marker = "[x]" if step.passed else "[ ]"
        lines.append(f"- {marker} {step.name}: {step.details}")

    lines.extend(
        [
            "",
            "## Sign-off",
            "",
            f"- QA/Owner Decision: {'Approved' if all_passed else 'Rejected'}",
            "- Release Note: Generated by `scripts/run_uat.py`",
        ]
    )
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path


def _assert_status(response: Any, expected: int, context: str) -> None:
    if response.status_code != expected:
        raise RuntimeError(f"{context} failed: expected {expected}, got {response.status_code}, body={response.text}")


def run_uat() -> tuple[list[UATStep], bool]:
    repo_backend = Path(__file__).resolve().parents[1]
    db_path = repo_backend / "uat_agentloopr.db"

    _set_uat_environment(db_path)
    from app.infrastructure.config.settings import get_settings

    get_settings.cache_clear()
    if db_path.exists():
        db_path.unlink()
    _run_migrations(repo_backend)

    steps: list[UATStep] = []

    try:
        from fastapi.testclient import TestClient
        from app.main import app

        with TestClient(app) as client:
            email = f"uat-{uuid4().hex[:8]}@example.com"

            register = client.post(
                "/api/v1/auth/register",
                json={"display_name": "UAT User", "email": email, "password": "StrongPass123"},
            )
            _assert_status(register, 201, "register")
            steps.append(UATStep("Auth Register", True, "User registration succeeded"))

            profile = client.post(
                "/api/v1/profile",
                json={"upwork_profile_id": "uat_profile", "proposal_template": "template"},
            )
            _assert_status(profile, 201, "profile_create")
            steps.append(UATStep("Profile Create", True, "Profile created"))

            intake = client.post(
                "/api/v1/jobs/intake",
                json={"job_url": f"https://www.upwork.com/jobs/flow~{uuid4().hex}"},
            )
            _assert_status(intake, 201, "job_intake")
            job_id = intake.json()["job"]["id"]
            steps.append(UATStep("Job Intake", True, "Job intake created"))

            manual = client.post(
                f"/api/v1/jobs/{job_id}/manual-markdown",
                json={"job_markdown": "## UAT Markdown\nManual content for deterministic UAT."},
            )
            _assert_status(manual, 200, "manual_markdown")
            steps.append(UATStep("Manual Markdown", True, "Manual fallback path works"))

            outputs = client.patch(
                f"/api/v1/jobs/{job_id}/outputs",
                json={"proposal_text": "UAT proposal", "loom_script": "UAT script"},
            )
            _assert_status(outputs, 200, "outputs_patch")
            steps.append(UATStep("Output Save", True, "Output persistence works"))

            connector = client.post(
                "/api/v1/connectors",
                json={
                    "connector_name": "google_docs",
                    "credential_ref": "oauth://google/uat-user",
                    "status": "pending_oauth",
                },
            )
            _assert_status(connector, 201, "connector_create")
            steps.append(UATStep("Connector Create", True, "Connector API works"))

            history = client.get("/api/v1/jobs")
            _assert_status(history, 200, "jobs_list")
            steps.append(UATStep("History List", True, "History listing works"))

            detail = client.get(f"/api/v1/jobs/{job_id}")
            _assert_status(detail, 200, "job_detail")
            steps.append(UATStep("Job Detail", True, "Job detail with output works"))

            metrics = client.get("/api/v1/metrics")
            _assert_status(metrics, 200, "metrics")
            steps.append(UATStep("Metrics Endpoint", True, "Metrics endpoint responds"))

    except Exception as exc:
        steps.append(UATStep("UAT Runtime", False, str(exc)))
        return steps, False
    finally:
        try:
            if db_path.exists():
                db_path.unlink()
        except OSError:
            pass

    return steps, all(step.passed for step in steps)


def main() -> int:
    started_at = datetime.now().astimezone()
    steps, passed = run_uat()
    finished_at = datetime.now().astimezone()
    repo_backend = Path(__file__).resolve().parents[1]
    report_path = _create_report(
        repo_backend=repo_backend,
        steps=steps,
        started_at=started_at,
        finished_at=finished_at,
    )
    print(f"UAT report written to: {report_path}")
    return 0 if passed else 1


if __name__ == "__main__":
    raise SystemExit(main())
