import asyncio
from datetime import UTC, datetime
from time import perf_counter
from typing import Any, cast
from uuid import uuid4

from fastapi import Request
from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
from starlette.responses import JSONResponse, Response

from app.infrastructure.config.settings import get_settings
from app.infrastructure.http.global_rate_limiter import global_rate_limiter
from app.infrastructure.http.idempotency import IdempotencyRecord, idempotency_store
from app.infrastructure.http.request_context import bind_request_id, reset_request_id
from app.infrastructure.logging.setup import get_logger
from app.infrastructure.observability.metrics import metrics_state

logger = get_logger(__name__)
settings = get_settings()
_IDEMPOTENT_METHODS = {"POST", "PATCH", "DELETE"}
_IDEMPOTENT_PATH_PREFIXES = (
    "/api/v1/jobs",
    "/api/v1/connectors",
    "/api/v1/profile",
)


class RequestContextMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next: RequestResponseEndpoint) -> Response:
        request_id = request.headers.get("x-request-id", str(uuid4()))
        token = bind_request_id(request_id)
        started_at = perf_counter()
        response: Response | None = None

        try:
            response = await call_next(request)
        finally:
            duration_ms = (perf_counter() - started_at) * 1000
            status_code = response.status_code if response else 500
            metrics_state.record_http_request(duration_ms=duration_ms, status_code=status_code)
            logger.info(
                "request.completed",
                extra={
                    "method": request.method,
                    "path": request.url.path,
                    "status_code": status_code,
                    "duration_ms": round(duration_ms, 2),
                },
            )
            reset_request_id(token)

        if response is None:
            raise RuntimeError("Response was not generated by request pipeline")

        response.headers["x-request-id"] = request_id
        return response


class RequestTimeoutMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next: RequestResponseEndpoint) -> Response:
        try:
            return await asyncio.wait_for(
                call_next(request),
                timeout=settings.request_timeout_seconds,
            )
        except TimeoutError:
            return JSONResponse(
                status_code=504,
                content={
                    "error": {
                        "code": "request_timeout",
                        "message": "Request timed out",
                        "details": {"timeout_seconds": settings.request_timeout_seconds},
                    }
                },
            )


class GlobalRateLimitMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next: RequestResponseEndpoint) -> Response:
        if request.url.path == "/health":
            return await call_next(request)

        client_host = request.client.host if request.client else "unknown"
        key = f"{client_host}:{request.method}:{request.url.path}"
        decision = global_rate_limiter.check_and_record(key)
        if not decision.allowed:
            return JSONResponse(
                status_code=429,
                content={
                    "error": {
                        "code": "too_many_requests",
                        "message": "Global request rate limit exceeded",
                        "details": {"retry_after_seconds": decision.retry_after_seconds},
                    }
                },
            )
        return await call_next(request)


class IdempotencyMiddleware(BaseHTTPMiddleware):
    async def dispatch(self, request: Request, call_next: RequestResponseEndpoint) -> Response:
        if request.method not in _IDEMPOTENT_METHODS:
            return await call_next(request)
        if not request.url.path.startswith(_IDEMPOTENT_PATH_PREFIXES):
            return await call_next(request)

        idempotency_key = request.headers.get("idempotency-key")
        if not idempotency_key:
            return await call_next(request)

        requester = request.cookies.get(settings.auth_cookie_name, "anonymous")
        cache_key = f"{requester}:{request.method}:{request.url.path}:{idempotency_key}"
        existing = idempotency_store.get(cache_key)
        if existing:
            replay = Response(
                content=existing.body,
                status_code=existing.status_code,
                media_type=existing.media_type,
                headers=existing.headers,
            )
            replay.headers["x-idempotent-replay"] = "true"
            return replay

        response = await call_next(request)
        if response.status_code >= 500:
            return response

        body = b""
        body_iterator = getattr(response, "body_iterator", None)
        if body_iterator is not None:
            async for chunk in cast(Any, body_iterator):
                body += chunk
        else:
            response_body = getattr(response, "body", b"")
            body = bytes(response_body)

        replay_headers = dict(response.headers)
        rebuilt = Response(
            content=body,
            status_code=response.status_code,
            media_type=response.media_type,
            headers=replay_headers,
        )

        idempotency_store.set(
            cache_key,
            IdempotencyRecord(
                created_at=datetime.now(UTC),
                status_code=rebuilt.status_code,
                media_type=rebuilt.media_type,
                body=body,
                headers=dict(rebuilt.headers),
            ),
        )
        return rebuilt
